Repository ROCm/hipSOLVER, pull requests merged in 2024-10, with the labels that each got.

#331 Convert change log to new format
  CHANGELOG.md
Labels: ci:docs-only

#330 Convert change log to new format
  CHANGELOG.md
Labels: ci:docs-only

#333 Add note to the readme file
  README.md
Labels: documentation, ci:docs-only

#334 Disable sparse functions by default when building a static library
  CMakeLists.txt
  library/src/amd_detail/dlopen/cholmod.cpp
  library/src/amd_detail/dlopen/load_function.hpp
  library/src/amd_detail/dlopen/rocsparse.cpp
Labels: ci:static-libraries
